# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inner_product_matrix_splines <- function(list_of_splines, from, to) {
    .Call(`_ghcm_inner_product_matrix_splines`, list_of_splines, from, to)
}

